---
title: "CSI-MTH 190: Intro to Data Science"
author: "Nicholas Schwab"
date: "today"

output: html_document

format:
  html:
    toc: true
    toc-depth: 1
    toc-float: true
    toc-location: left
    toc-title: ""
    df-print: kable
    smooth-scroll: true
---

```{=html}
<style>
h1{font-weight: 400;}
</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message=FALSE, warning = FALSE, eval = TRUE,
  fig.width = 16/2, fig.height = 9/2
)

# tidyverse R packages:
library(tidyverse)

# CRAN R packages:
library(knitr)
```


# Lectures
Part 1: Visualizations

# Week 1

-   [1. Overview of Intro to Data Science](./course-materials/lectures/1_Overview_of_the_course.qmd)

-   [Live Coding: Introduction to R and RStudio](https://rstudio.hcc.edu/auth-sign-in?appUri=%2F)

-   [2. Brief History of R](./course-materials/lectures/2_Brief-R-history.qmd)

-   [3. Basic Statistics](./course-materials/lectures/3_Basic_Statistics.qmd)


# Week 2

-   [4. Where does Data Comes From](./course-materials/lectures/4_where_does_data_come_from.qmd)

-   [5. Notes on Style](./course-materials/lectures/5_notes_on_style.qmd)

-   [6 Data Frames Variable Types Tidy Data](./course-materials/lectures/6_Data_Frames_Variable_Types_Tidy_Data.qmd)

-   [7 Data Ethics part 1](./course-materials/lectures/7_ethics_part_1.qmd)


# Week 3 

-   [8 The ggplot cheatsheet](https://github.com/rstudio/cheatsheets/blob/553af35d9bda98715ed5fedfd8709ade4ba12b76/data-visualization.pdf)

-   [9 Taxonomy of Data Graphics (categorical)](./course-materials/lectures/9_taxonomy_of_graphs_categorical.qmd)

-   [10 Taxonomy of Data Graphics (numeric)](./course-materials/lectures/10_taxonomy_of_graphs_numeric_part_2.qmd)

-   [11 Color talk](./course-materials/lectures/11_color_theory.qmd)

# Week 4

-   [12 Data Ethics part 2](./course-materials/lectures/12_ethics_part_2.qmd)

-   [13 Building a graph](./course-materials/lectures/13_Building_a_graph.qmd)

-   [14 Data Ethics and Tidy Data Examples](./course-materials/lectures/14_in_class_ethic_examples.qmd)

-   [14 Set up for Lab 4]()

# Week 5

-   [Project 1 Intro](./course-materials/lectures/14_2_introduce_project_1.qmd)

# Week 6

Part 2: Wrangling

-   [15 Lecture on the five verbs](./course-materials/lectures/15_Lecture_on_five_verbs.qmd)

-   [16 Dplyr Cheat sheet](https://github.com/rstudio/cheatsheets/blob/553af35d9bda98715ed5fedfd8709ade4ba12b76/data-transformation.pdf)

-   [17 Ethics Part 3](./course-materials/lectures/17_ethic_part_3.qmd)

# Week 7

-   [18 Joins ](./course-materials/lectures/18_joins.qmd)


# Week 8


-   [19 Pivots](./course-materials/lectures/19_pivots.qmd)

-   [20 Scraping and cleaning](./course-materials/lectures/20_scraping.qmd)

# Week 9 

-   [21 Cleaning Quarto Documents](./course-materials/lectures/21_quarto_docs_and_working_dir.qmd)

-   [Project 2 Intro]()

# Week 10

Part 3: Application - Maps

-   [22 Maps part 1](./course-materials/lectures/22_maps-ggplot.qmd)

-   [23 Maps part 2](./course-materials/_labs/non_lab_maps_2/)

-   [24 Maps part 3](./course-materials/lectures/24_Choropleth_maps.qmd)

# Week 11

-   [24 Maps part 3](./course-materials/lectures/24_Choropleth_maps.qmd)

-   [25 Finding Data Demo]() (see canvas)

# Week 12

-   [Project 3 Intro]()

# Week 13

Part 4: Parallel to SQL

-   [26 SQL](/course-materials/lectures/26_Intro_to_SQL.qmd)

-   [27 SQL-Practice.com](https://www.sql-practice.com/)

# Week 14

-   [28 SQL in R]()

-   [Lab 8]()

# Week 15

-   [Project 4 Intro]()


